/**:
  ros__parameters:
    namespace: "drone0"
    use_sim_time: True
    verbose: False
    speed_value: 0.5
    altitude_speed_value: 0.5
    turn_speed_value: 0.5
    position_value: 1.00
    altitude_value: 1.00
    turn_angle_value: 0.78
    speed_frame_id: "earth"
    pose_frame_id: "earth"
    initial_mode: "pose"