/**:
  ros__parameters:
    image_width: 1280
    image_height: 720
    camera_name: cam_wide03
    camera_matrix:
      rows: 3
      cols: 3
      data: [694.95934306, 0.000000, 642.99590236, 0.000000, 697.78338843, 376.52641891, 0.000000, 0.000000, 1.000000]
    distortion_model: plumb_bob
    distortion_coefficients:
      rows: 1
      cols: 5
      data: [-0.43606792 , 0.17578458 ,-0.0049836 , 0.00522144, -0.02809072]
    rectification_matrix:
      rows: 3
      cols: 3
      data: [0.999978, 0.002789, -0.006046, -0.002816, 0.999986, -0.004401, 0.006034, 0.004417, 0.999972]
    projection_matrix:
      rows: 3
      cols: 4
      data: [393.653800, 0.000000, 322.797939, 0.000000, 0.000000, 393.653800, 241.090902, 0.000000, 0.000000, 0.000000, 1.000000, 0.000000]
