/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz (default: 100.0)
    info_freq: 10.0  # Hz (default: 10.0)
    plugin_name: "controller_plugin_speed_controller"
    plugin_config_file: ""  # (default: plugin/config/default_controller.yaml)
    plugin_available_modes_config_file: ""  # (default: plugin/config/available_modes.yaml)
