/**:
  ros__parameters:
    controller_node: "holi"    # Name of the controller manager node to update the mass parameter.
    force_param_name: ""    # Name of the mass parameter in the controller to be updated.
    mass_param_name: ""    # Name of the mass parameter in the controller to be updated.
    alpha: 0.5             # Low-pass filter coefficient for the force error estimation.
    n_samples: 20           # Number of samples to average the force error estimation.
    initial_force_error: 0.6  # Initial force error value.
    threshold_time_sync: 0.0  # Time threshold for synchronizing IMU and force command messages (s).
    fz_update_error: 50.0       # Factor to update the force error (filter the stack and update force_error_) (Hz).
    minimum_error: 0.0      # Minimum force error to be considered valid. (N)
    maximum_error: 3.0      # Maximum force error to be considered valid. (N)
    debug:
      force_error_topic: "debug/param_estimation/force_error"  # Topic to publish the current estimated thrust error for debugging.
      force_filtered_error_topic: "debug/param_estimation/force_filtered_error"  # Topic to publish the filtered thrust error for debugging.
      force_update_error_topic: "debug/param_estimation/force_update_error"  # Topic to publish the force error used for updating the parameter for debugging.
      force_limited_error_topic: "debug/param_estimation/force_limited_error"  # Topic to publish the limited force error for debugging.