/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz of platform commands send
    info_freq: 10.0  # Hz of platform info publish
    enable_takeoff_platform: false  # Enable takeoff platform, only for debugging purposes
    enable_land_platform: false  # Enable land platform, only for debugging purposes
