name: build-galactic

on:
  pull_request:
    branches:
      - main 
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    container:
      image: osrf/ros:galactic-desktop
    strategy:
      matrix:
        os: [ubuntu-22.04]
      fail-fast: false
    steps:
      # - name: Install deps
      #   run: sudo apt-get update && sudo apt-get install -y wget python3-vcstool python3-colcon-coveragepy-result libfl-dev tmux python3-rosdep python3-pip python3-colcon-common-extensions && pip3 install pyros-genmsg 
      # - name: Setup ros
      #   uses: ros-tooling/setup-ros@v0.3
      #   with:
      #     required-ros-distributions: galactic 
      - name: build and test
        uses: ros-tooling/action-ros-ci@v0.2
        with:
          package-name: as2_core as2_msgs as2_controller as2_tello_platform as2_motion_reference_handlers as2_behaviors
          target-ros2-distro: galactic 
          # colcon-defaults: |
          #   {
          #     "test": {
          #       "parallel-workers" : 1
          #     }
          #   }
          colcon-mixin-name: coverage-gcc
          colcon-mixin-repository: https://raw.githubusercontent.com/colcon/colcon-mixin-repository/master/index.yaml
      # - name: Codecov
      #   uses: codecov/codecov-action@v1.2.1
      #   with:
      #     file: ros_ws/lcov/total_coverage.info
      #     flags: unittests
      #     name: codecov-umbrella
      #     # yml: ./codecov.yml
      #     fail_ci_if_error: false
